Calculaber/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from calculaber_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('calculaber_app.urls')),
    path('',include('users_app.urls')),
    path('project/<int:pk>/detail/',views.ProjectDetailView.as_view(),name='project_detail'),
    path('project/<int:pk>/delete/',views.ProjectDeleteView.as_view(),name='project_delete'),
    path('project/<int:pk1>/detail/<int:pk2>/',views.ObjectDetailView.as_view(),name='object_detail'),
    path('project/<int:pk>/detail/extra_expense/',views.ExtraExpenseDetailView.as_view(),name='extra_expense_detail'),
    path('extra_expense/<int:pk>/delete',views.ExtraExpenseDeleteView.as_view(),name='extra_expense_delete'),
    path('object/<int:pk>/delete',views.ObjectDeleteView.as_view(),name='object_delete'),
    path('material/<int:pk>/delete/',views.MaterialDeleteView.as_view(),name='material_delete'),
    path('material_object/<int:pk>/delete/',views.MaterialObjectDeleteView.as_view(),name='material_object_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

calculaber_app/urls.py
from django.urls import path
from calculaber_app import views

app_name='calculaber_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('info/',views.account_info,name='account_info'),
    path('material/',views.MaterialListView.as_view(),name='material_list'),
    #path('sensorlist/',views.SensorListView.as_view(),name='sensor_list'),
]

users_app/urls.py
from django.urls import path, include
from users_app import views

app_name='users_app'
urlpatterns = [
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    #path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('generate_account/',views.generate_account,name='generate_account'),
]

calculaber_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# import uuid

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    create_date = models.DateTimeField(default=timezone.now)
    project_pic = models.ImageField(upload_to='project_pics', default="project_pics/default.png", blank=True)

    def __str__(self):
        return f"{self.id} - {self.name}"


class Material(models.Model):
    class UnitsChoice(models.TextChoices):
        setup_0 = '0', "kus"
        setup_1 = '1', "m2"
        setup_2 = '2', "m3"
        setup_3 = '3', "m"
        setup_4 = '4', "cm"
        setup_5 = '5', "mm"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    margin = models.DecimalField(default=20, blank=False, decimal_places=2, max_digits=65, )
    price = models.DecimalField(default=0, blank=False, decimal_places=2, max_digits=65)
    create_date = models.DateTimeField(default=timezone.now)
    units = models.CharField(
        max_length=2,
        choices=UnitsChoice.choices,
        default=UnitsChoice.setup_0)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.price} czk ({self.get_units_display()})"


class Object(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.project.name}"


class MaterialObject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    object = models.ForeignKey(Object, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    amount = models.DecimalField(default=0, blank=False, decimal_places=2, max_digits=65)
    create_date = models.DateTimeField(default=timezone.now, blank=True)

    customized = models.BooleanField(default=False)
    margin = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=65)
    price = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=65)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.amount} {self.material.get_units_display()}"


class ExtraExpense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(default=0, blank=False, null=True, decimal_places=2, max_digits=65)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.project.name}"


class MaterialTag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    tag = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.id} - {self.tag} - {self.material.name}"


class ObjectTag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    object = models.ForeignKey(Object, on_delete=models.CASCADE)
    tag = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.id} - {self.tag} - {self.object.name}"

calculaber_app/views.py
from django.shortcuts import render
from django.views.generic import ListView,UpdateView, DeleteView
from django.http import HttpResponseRedirect,JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . import models,forms
from django.contrib.auth.decorators import login_required
from django.db.models import Sum,F,Case,When,DecimalField
from django.core.serializers.json import DjangoJSONEncoder
import json

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def index(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            project_form=forms.CreateProjectForm(request.POST, request.FILES)
            if project_form.is_valid():
                obj = models.Project()
                obj.name=project_form.cleaned_data.get("name")
                obj.project_pic=project_form.cleaned_data.get("project_pic")
                obj.user_id=request.user.id
                obj.save()

                return HttpResponseRedirect(request.path_info)

        projects=models.Project.objects.filter(user=request.user.id)
        return render(request,'calculaber_app/project_list.html',{'form':forms.CreateProjectForm,'projects':projects})
    else:
        return render(request,'calculaber_app/index.html')

@login_required
def account_info(request):
    return render(request,'calculaber_app/new_account_info.html')

class ProjectDetailView(LoginRequiredMixin,ListView):
    context_object_name = 'project_detail'
    template_name='calculaber_app/project_detail.html'
    model=models.Object

    def calculate_object_price(self,user_id,project_id,object_id=None):
        not_customized=Sum((F('materialobject__material__price')*(100+F('materialobject__material__margin')))/100*F('materialobject__amount'))#Sum((F('materialobject__material__price')*(1+F('materialobject__material__margin')/100))*F('materialobject__amount'))
        customized=Sum((F('materialobject__price')*(100+F('materialobject__margin')))/100*F('materialobject__amount'))
        if object_id is None:
            selected_objects=models.Object.objects.filter(user=user_id,project=project_id).select_related()
        else:
            selected_objects=models.Object.objects.filter(user=user_id,project=project_id,id=object_id).select_related()
        complete_data=selected_objects.values('id','name','create_date')

        final_set = complete_data.annotate(object_price=Case(
            When(materialobject__customized=True,then=customized),
            When(materialobject__customized=False,then=not_customized),
            default=0,
            output_field=DecimalField()
            )).order_by('name')
        return final_set

    def get_context_data(self, **kwargs):
        context = super (). get_context_data (** kwargs)
        context.update({
         'form':forms.CreateObjectForm,
         'project':models.Project.objects.filter(user=self.request.user,id=self.kwargs['pk']).values()[0],
         'form_update':forms.CreateProjectForm,
         'form_tag':forms.ObjectTagForm,
         'project_json':json.dumps(list(models.Project.objects.filter(user=self.request.user,id=self.kwargs['pk']).values()), cls=DjangoJSONEncoder),
         'extra_expense_json':json.dumps(list(models.ExtraExpense.objects.filter(user=self.request.user,project=self.kwargs['pk']).values()), cls=DjangoJSONEncoder),
         'tag_list':json.dumps(list(models.ObjectTag.objects.filter(user=self.request.user).values('object_id','tag')), cls=DjangoJSONEncoder),
         'all_objects':json.dumps(list(models.Object.objects.filter(user=self.request.user).select_related('project').values('id','name','project_id','project__name')), cls=DjangoJSONEncoder),
        })
        return context

    def get_queryset(self):
        final_set=self.calculate_object_price(self.request.user,self.kwargs['pk'])
        return json.dumps(list(final_set.values('id','name','create_date','object_price')), cls=DjangoJSONEncoder)

    def post(self, request, *args, **kwargs):
        if is_ajax(request=request):
            if request.POST.get('type')=="new":
                instance = models.Object()
                instance.name=request.POST.get("name")
                instance.project_id=request.POST.get("project")
                instance.user=request.user
                instance.save()

                for tag in request.POST.getlist('tags[]'):
                    tag_instance = models.ObjectTag()
                    tag_instance.object=instance
                    tag_instance.user=self.request.user
                    tag_instance.tag=tag
                    tag_instance.save()

                return JsonResponse(data={
                                "id":instance.id,
                                'name':instance.name,
                                'create_date':instance.create_date,
                                'tag_list':json.dumps(list(models.ObjectTag.objects.filter(object_id=instance.id,user=self.request.user).values('object_id','tag')), cls=DjangoJSONEncoder),
                                },status=200)

            elif request.POST.get('type')=="duplicate":
                instance=models.Object.objects.get(id=request.POST.get("id"))
                instance.pk=None
                instance.project_id=request.POST.get("project")
                instance.save()

                for tag in list(models.ObjectTag.objects.filter(object_id=request.POST.get("id"),user=self.request.user).values('tag')):
                    tag_instance = models.ObjectTag()
                    tag_instance.object=instance
                    tag_instance.user=self.request.user
                    tag_instance.tag=tag['tag']
                    tag_instance.save()

                for item in models.MaterialObject.objects.filter(object_id=request.POST.get("id")):
                    new_item=models.MaterialObject()
                    new_item.material=item.material
                    new_item.object=instance
                    new_item.name=item.name
                    new_item.amount=item.amount
                    new_item.user=request.user
                    new_item.save()

                duplicated_object=self.calculate_object_price(self.request.user,request.POST.get("project"),instance.id)
                return JsonResponse(data={
                                "object":json.dumps(list(duplicated_object.values('id','name','create_date','object_price')), cls=DjangoJSONEncoder),
                                'tag_list':json.dumps(list(models.ObjectTag.objects.filter(object_id=instance.id,user=self.request.user).values('object_id','tag')), cls=DjangoJSONEncoder),
                                },status=200)

        else:
            if "update_project_sub" in request.POST:
                object_form=forms.CreateProjectForm(request.POST, request.FILES)
                if object_form.is_valid():
                    obj=models.Project.objects.get(id=self.kwargs['pk'])
                    obj.name=object_form.cleaned_data.get("name")
                    if not object_form.cleaned_data.get("project_pic") is None:
                        obj.project_pic=object_form.cleaned_data.get("project_pic")
                    obj.save()

            return HttpResponseRedirect(request.path_info)

class ProjectDeleteView(LoginRequiredMixin,DeleteView):
    model=models.Project
    success_url=reverse_lazy('calculaber_app:index')

class MaterialListView(LoginRequiredMixin,ListView):
    context_object_name = 'material_list'
    template_name='calculaber_app/material_list.html'
    model=models.Material

    def get_context_data(self, **kwargs):
        context = super (). get_context_data (** kwargs)
        material=models.Material.objects.filter(user=self.request.user).values('id','name','margin','price','units')

        context.update({
         'form':forms.CreateMaterialForm,
         'form_update':forms.UpdateMaterialForm,
         'tag_form':forms.MaterialTagForm,
         'units_list':json.dumps([choice[1] for choice in models.Material._meta.get_field('units').choices], cls=DjangoJSONEncoder),
         'tag_list':json.dumps(list(models.MaterialTag.objects.filter(user=self.request.user).values('material_id','tag')), cls=DjangoJSONEncoder),
         'material_list':json.dumps(list(material), cls=DjangoJSONEncoder)
         })
        return context

    def post(self, request, *args, **kwargs):
        if is_ajax(request=request):
            if request.POST.get('type')=="delete":
                instance = models.Material.objects.get(id=request.POST.get('item_id'),user=self.request.user)
                instance.delete()
                return JsonResponse(data={"delete":request.POST['item_id']},status=200)

            elif request.POST.get('type')=="update":
                instance = models.Material.objects.get(id=request.POST.get('item_id'),user=self.request.user)
                instance.name=request.POST.get("name")
                instance.margin=request.POST.get("margin")
                instance.price=request.POST.get("price")
                instance.units=request.POST.get("units")
                instance.save()

                tags=list(models.MaterialTag.objects.filter(user=self.request.user,material_id=request.POST.get('item_id')).values('tag'))
                tags_lst=set([tag['tag'] for tag in tags])
                tags_lst_POST=set(request.POST.getlist('tags[]'))

                if tags_lst!=tags_lst_POST:
                    for tag_delete in (tags_lst-tags_lst_POST):
                        tag_instance = models.MaterialTag.objects.get(material_id=request.POST.get('item_id'),user=self.request.user,tag=tag_delete)
                        tag_instance.delete()

                    for tag in (tags_lst_POST-tags_lst):
                        tag_instance = models.MaterialTag()
                        tag_instance.material_id=request.POST.get('item_id')

calculaber_app/templates/calculaber_app/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.2/datatables.min.css"/>-->
    <!--<link rel="stylesheet" href="{% static 'css/style.css' %}">-->
    <title>calculaber</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #18A999;">
      <div class="container">
      <a class="navbar-brand" href={% url 'calculaber_app:index' %} title='calculaber'>
       <img src="/media/logo/logo.png" height="50" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse text-center" id="navbarTogglerDemo03">



          {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'calculaber_app:index' %}">Projekty</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'calculaber_app:material_list' %}">Materiály</a>
            </li>

            {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin Console</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users_app:logout' %}">Odhlásit</a>
            </li>
          {% else %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users_app:generate_account' %}">Registrace</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users_app:user_login' %}">Přihlást</a>
            </li>
          {% endif %}
        </ul>


      </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    <!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>-->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    {% block jquery %}
    {% endblock %}
  </body>
</html>

calculaber_app/templates/calculaber_app/layout.html
{% extends "calculaber_app/main-layout.html" %}
{% block body_block %}
{% include "calculaber_app/navbar.html" %}
  {% block content_block %}
  {% endblock %}
{% endblock %}

calculaber_app/templates/calculaber_app/main-layout.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Calculaber</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet">
  </head>
  <body>
      {% block body_block %}
      {% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    {% block jquery %}
    {% endblock %}
  </body>
</html>

calculaber_app/templates/calculaber_app/material_list.html
{% extends "calculaber_app/main-layout.html" %}
{% block body_block %}
{% include "calculaber_app/navbar.html" %}
<main>
  <div class="path">
      <a href="{% url 'calculaber_app:material_list' %}" class="path__link">Materiály</a>
  </div>

  <header class="header header--flex">
      <h1 class="header__title">Materiály</h1>
      <button id="new_material" data-toggle="modal" data-target="#NewMaterial">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon-new" width="40" height="40" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
        </svg>
      </button>
  </header>
  {% csrf_token %}
  <table class="table-material" id="mydatatable">
    <thead>
      <tr class="table-material__head">
        <th class="table-material__item">Název</th>
        <th class="table-material__margin">Margin</th>
        <th class="table-material__price">Cena</th>
        <th class="table-material__units">Jednotky</th>
        <th class="table-material__tags">Tags</th>
      </tr>
    </thead>
    <tbody>

    </tbody>

  </table>
  <button class="table__new" title="dil" data-toggle="modal" data-target="#NewMaterial">
    <p class="table__new--text">+ Nový materiál</p>
  </button>
  {% csrf_token %}
  {% include "calculaber_app/new_material_modal.html" %}
  {% include "calculaber_app/update_material_modal.html" %}
</main>
{% endblock %}
{% block jquery %}
{% load static %}
{{ material_list_test|json_script:"json_data" }}
<script type="text/javascript">
  function FormatNumber(number_text) {
    var value = (Number(number_text)).toLocaleString(
      undefined,
      { minimumFractionDigits: 2 }
    );
    return value;
  };
</script>
<script type="text/javascript">
  var material = {{ material_list|safe }};
  var choice_array = {{ units_list|safe }};
  var tag_array = {{ tag_list|safe }};
  var new_tag_array=[];
  var edit_button_content="<div class='icon-edit'><svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' viewBox='0 0 16 16'><path d='M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z'/></svg></div>";
  var remove_button_content="<div class='icon-remove'><svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' viewBox='0 0 16 16'><path d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/><path fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/></svg></div>";
  document.addEventListener("DOMContentLoaded", function() {
      var table = document.getElementById("mydatatable").getElementsByTagName("tbody")[0];
      var tr="";
      console.log('here');
      material.forEach(x=>{
         tr+="<tr class='table-material__data' id='" + x.id + "'>";
         tr+="<td class='table-material__item name'>"+x.name+'</td>'+"<td class='table-material__margin margin'>"+FormatNumber(x.margin)+' %</td>'+"<td class='table-material__price price'>"+FormatNumber(x.price)+' Kč</td>'+"<td class='table-material__units units'>"+choice_array[x.units]+'</td>';
         tr+="<td class='table-material__tags'>";
         tr+="<div class='tag__popup'>";
           tag_array.filter(item => item.material_id === x.id).forEach(i=>{
             tr+="<div class='tag-box'><p class='tag tag--flex'>" + i.tag + "</p></div>";
           });
         tr+="</div>";
         tr+="</td>";
         tr+="<td class='icon'>";
         tr+="<button class='update' data-toggle='modal' data-target='#UpdateMaterial'>" + edit_button_content + "</button>";
         tr+="<form class='delete_material' method='POST'><button class='remove' name='delete_material_sub' type='submit' onclick=\"return confirm('Opravdu chcete materiál smazat?')\">" + remove_button_content + "</button></form>";
         tr+="</td>";
         tr+='</tr>';
      })
      table.innerHTML+=tr;
  });
</script>
<script type="text/javascript" src="{% static 'js/material_list.js' %}" charset="utf-8"></script>
{% endblock %}

calculaber_app/templates/calculaber_app/new_extra_expense_modal.html
<div class="modal fade" id="NewExtraExpense" tabindex="-1" role="dialog" aria-labelledby="Nový výdaj" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Nový výdaj</h5>

      </div>
      <form class="new_extra_expense" method="post" enctype="multipart/form-data">
        <div class="modal-body">
          <div class="form-group">
            <label for="new_expense_name" class="form-label">Název výdaje</label>
            {{ create_form.name }}
          </div>
          <div class="form-group">
            <label for="new_expense_description" class="form-label">Popis</label>
            {{ create_form.description }}
          </div>
          <label class="form-label" for="new_expense_price">Cena</label>
          <div class="form-group input-group">
            {{ create_form.price }}
            <div class="input-group-append">
              <span class="input-group-text" id="price_format">CZK</span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="button button--secondary" data-dismiss="modal">Zavřít</button>
          <button type="submit" name="new_extra_expense_sub" class="button button--primary" value="Přidat výdaj">Přidat</button>

        </div>
      </form>
    </div>
  </div>
</div>

calculaber_app/templates/calculaber_app/new_object_modal.html
<div class="modal fade" id="NewObject" tabindex="-1" role="dialog" aria-labelledby="Nový objekt" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Nový objekt</h5>

      </div>
      <form class="new_object" method="post" enctype="multipart/form-data">
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label" for="{{ form.name.id_for_label }}">Název</label>
            {{ form.name }}
          </div>
          <div class="form-group">
            {{ form_tag.tag }}
          </div>
          <div class="tag__popup">

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="button button--secondary" data-dismiss="modal">Zavřít</button>
          <button type="submit" name="new_object_sub" class="button button--primary">Přidat</button>

        </div>
      </form>
    </div>
  </div>
</div>

calculaber_app/templates/calculaber_app/object_confirm_delete.html
{% extends "calculaber_app/main-layout.html" %}
{% block body_block %}
{% include "calculaber_app/navbar.html" %}
<main>
  <div class="container">
    <form method="post">
      {% csrf_token %}
      <div class="danger__container">

          <h1>{{ object.name }}</h1>

          <p class="danger__message">Jste si jistí, že chcete objekt <span class="bold">{{ object.name }}</span> smazat?</p>

          <div class="button__container">
              <a class="button button--secondary button--margin" href="{% url 'object_detail' pk1=object.project.id pk2=object.pk %}">Zavřít</a>
              <button type="submit" class="button button--danger button--margin">Smazat</button>
          </div>
      </div>

  </div>
</main>

{% endblock %}